project:
  name: "AutoVision Analysis"

input:
  youtube:
    video_urls:
      - "https://www.youtube.com/watch?v=example1"
      - "https://www.youtube.com/watch?v=example2"
    download_options:
      quality: "best"
      format: "mp4"